#!/usr/bin/env bash

if [[ $MIRROR_ENV == "" ]]
then
  docker build --build-arg VERSION=${VERSION_ENV}  -t agirish/zookeeper:${VERSION_ENV} -t agirish/zookeeper:${VERSION_ENV}-centos .
else
  docker build --build-arg VERSION=${VERSION_ENV} --build-arg MIRROR=${MIRROR_ENV} -t agirish/zookeeper:${VERSION_ENV} -t agirish/zookeeper:${VERSION_ENV}-centos .
fi