apiVersion: v1
kind: Service
metadata:
  namespace: apache
  name: zk-service
spec:
  ports:
  - name: client
    port: 2181
  - name: server
    port: 2888
  - name: leader-election
    port: 3888
  selector:
   app: zk-app
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: apache
  name: zk
spec:
  serviceName: zk-service
  replicas: 1
  template:
    metadata:
      labels:
        app: zk-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - zk-app
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: zk-pod
        imagePullPolicy: Always
        image: agirish/zookeeper:3.4.10
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
